#include <stdlib.h>
#include <stdio.h> 

void write_pgm_image(void *image, int maxval, int xsize, int ysize, const char *image_name)
{
  FILE* image_file;
  image_file = fopen(image_name, "w"); 
  int color_depth;

  color_depth = 1 + (maxval > 255);

  fprintf(image_file, "P5\n# generated by\n# put here your name\n%d %d\n%d\n", xsize, ysize, maxval);
  fwrite(image, 1, xsize * ysize * color_depth, image_file);
  fclose(image_file);
}